go_mod_prefix: github.com/software-t-rex/monospace
js_package_manager: ^pnpm@7.27.0
projects:
    apps/monospace: internal
    apps/test-go: local
    gomodules/colors: internal
    gomodules/go-jobexecutor: git@github.com:software-t-rex/go-jobExecutor.git
    gomodules/scaffolders: internal
