# yaml-language-server: $schema=https://raw.githubusercontent.com/software-t-rex/monospace/main/apps/monospace/schemas/monospace.schema.json
go_mod_prefix: github.com/software-t-rex/monospace
js_package_manager: ^pnpm@7.30.0
projects:
    apps/monospace: internal
    gomodules/colors: internal
    gomodules/dag: local
    gomodules/go-jobexecutor: git@github.com:software-t-rex/go-jobExecutor.git
    gomodules/js-packagemanager: git@github.com:software-t-rex/js-packagemanager.git
    gomodules/packageJson: git@github.com:software-t-rex/packageJson.git
    gomodules/scaffolders: internal
    packages/monospace: internal
projects_aliases:
    executor: gomodules/go-jobexecutor
    jspm: gomodules/js-packagemanager
    monospace: apps/monospace
    packageJson: gomodules/packageJson
pipeline:
    tidy:
        cmd: [go, mod, tidy]
    executor#test:
        cmd: [test.sh]
    monospace#doc:
        cmd: [./gendoc.sh, -md, -man]
    monospace#build:
        cmd: [goreleaser, release, --clean, --skip-publish]
        dependsOn: ["test", packages/monospace#update-package-json]
    monospace#buildnext:
        cmd: [goreleaser, build, --config, ./.goreleaser-next.yaml, --id, monospace-next, --snapshot, --clean, --single-target]
    monospace#test:
        dependsOn: [packageJson#test, executor#test, jspm#test]
        cmd: [test.sh]
    packageJson#test:
        cmd: [test.sh]
    jspm#test:
        cmd: [test.sh]
        dependsOn: [packageJson#test]
    monospace#diforigins:
        cmd: [git, diff, --name-only, origin/main]
    executor#diforigins:
        cmd: [git, diff, --name-only, origin/main]
    jspm#diforigins:
        cmd: [git, diff, --name-only, origin/main]
    packageJson#diforigins:
        cmd: [git, diff, --name-only, origin/main]
    packages/monospace#build: {}
    packages/monospace#update-package-json: {}
