# yaml-language-server: $schema=https://raw.githubusercontent.com/software-t-rex/monospace/main/apps/monospace/schemas/monospace.schema.json
go_mod_prefix: github.com/software-t-rex/monospace
js_package_manager: ^pnpm@7.27.0
projects:
    apps/monospace: internal
    gomodules/colors: internal
    gomodules/dag: local
    gomodules/go-jobexecutor: git@github.com:software-t-rex/go-jobExecutor.git
    gomodules/js-packagemanager: git@github.com:software-t-rex/js-packagemanager.git
    gomodules/packageJson: git@github.com:software-t-rex/packageJson.git
    gomodules/scaffolders: internal
projects_aliases:
    executor: gomodules/go-jobexecutor
    monospace: apps/monospace
    packageJson: gomodules/packageJson
pipeline:
    executor#test:
        cmd: [test.sh]
    monospace#doc:
        cmd: [./gendoc.sh, -md]
    monospace#test:
        dependsOn: [packageJson#test, executor#test]
        cmd: [test.sh]
    monospace#tidy:
        cmd: [go, mod, tidy]
    packageJson#test:
        cmd: [test.sh]
